### ISSUE TITLE
最新版本，无法post空对象

### ISSUE THREAD

**Issue by hwangjr** [bboyfeiyu/AndroidEventBus#23]
EventBus.getDefault().post(null, LoginEvent.TAG_EVENT);
空指针异常~~
看了下源码，里面有做类型转化。。

``` bash
07-28 18:28:49.449: E/AndroidRuntime(17063): java.lang.NullPointerException
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at org.simple.eventbus.EventBus.post(EventBus.java:188)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at co.sihe.hongmi.fragment.settings.SettingFragment$4.onClick(SettingFragment.java:88)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at android.view.View.performClick(View.java:4633)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at android.view.View$PerformClick.run(View.java:19323)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at android.os.Handler.handleCallback(Handler.java:733)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at android.os.Looper.loop(Looper.java:157)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
07-28 18:28:49.449: E/AndroidRuntime(17063): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bboyfeiyu** [comment]
一直不支持post空对象。

**Comment by hwangjr** [comment]
那我比较疑惑的就是，如果没有传对象，仅仅只是想通知的话，那不是也要自己手动构建一个对象丢过去？还是有其他更优雅的做法？

**Comment by bboyfeiyu** [comment]
@hwangjr 需要支持空消息，我这边没有空，可以自行实现，欢迎给主仓库提交pr。

**Comment by bboyfeiyu** [comment]
@hwangjr 这位同学实现了一下，可以试试他的这个。https://github.com/lixi0912/AndroidEventBus/tree/dev 。

**Comment by hwangjr** [comment]
前段时间忙项目，今天整理了并PULL给你了，OK的话可以考虑merge~~ ^-^
